name: Build and release Next.js web application
on:push
jobs:
  build-project:
    name: Build Next.js application
    runs-on: ubuntu-latest
    steps:
        name: Checkout code
        uses: action/learnning_nextjs
        name: Install NPM dependencies
        run: npm install
        name: Build static website
        run: npm run build
    